apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: compute-secret
rules:
- apiGroups:
  - ""
  resourceNames:
  - compute-secret
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: comput-secret
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: compute-secret
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: deploy@test.com
