apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: cka-1202-role
  namespace: cka
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: ckacs
  namespace: cka
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: cka-1202-rb
  namespace: cka
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cka-1202-role
subjects:
- kind: ServiceAccount
  name: ckacs
  namespace: cka
