apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      env:
        # Define the environment variable
        - name: PLAYER_INITIAL_LIVES # Notice that the case is different here
                                     # from the key name in the ConfigMap.
          valueFrom:
            configMapKeyRef:
              name: envcm           # The ConfigMap this value comes from.
              key: testkey # The key to fetch.
      envFrom:
        - configMapRef:
            name: secondenvcm
        - secretRef:
            name: firstsecret
        - secretRef:
            name: thirdsecret
      volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
      - name: secret
        mountPath: "/secret"
        readOnly: true
  volumes:
    # You set volumes at the Pod level, then mount them into containers inside that Pod
    - name: config
      configMap:
        # Provide the name of the ConfigMap you want to mount.
        name: propcm
    - name: secret
      secret:
        secretName: secondsecret
