apiVersion: v1
kind: Pod
metadata:
  name: nginxtestpod
spec:
  volumes:
    - name: testpvc
      persistentVolumeClaim:
        claimName: testpvc
  containers:
    - name: nginxtestpod
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: testpvc
