apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: php-nodeport
  name: php-nodeport
spec:
  ports:
  - name: php-nodeport
    port: 80
    protocol: TCP
  selector:
    run: php-apache
  type: NodePort
status:
  loadBalancer: {}
