apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: phpclusterip
  name: phpclusterip
spec:
  ports:
  - name: 80-80
    port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    run: php-apache
  type: ClusterIP
status:
  loadBalancer: {}
