apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: phplb
  name: phplb
spec:
  ports:
  - name: 8000-80
    port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    run: php-apache
  type: LoadBalancer
status:
  loadBalancer: {}
